#version:"3.9":

services:

  postgres:
    image: postgres:16
    container_name: career-postgres
    restart: unless-stopped
    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
volumes:
  postgres_data:
