"""Update resume schema

Revision ID: 431edaf59205
Revises: 30399fece5b5
Create Date: 2026-07-09 16:38:49.514852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431edaf59205'
down_revision: Union[str, Sequence[str], None] = '30399fece5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('resumes', sa.Column('extracted_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_text')
    op.drop_column('resumes', 'file_type')
    # ### end Alembic commands ###
